\begin{question}
Consider the following linear regression 
$$
Y_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \dots + \beta_p X_{ip} + \epsilon_i,
$$
where $X_{i1}=1$ for all $i=1,\dots,n$. 
\begin{answerlist}
\item Show that Assumption 2 (exogeneity) is violated if some of the regressors are correlated (i.e.~$\operatorname{Cov}(X_{ik},\epsilon_i)\neq 0$ for at least one $k=0,\dots,p$) with the error term.
\end{answerlist}
\end{question}

\begin{solution}
\begin{answerlist}
\item The exogeneity assumption states that
$$
E(\epsilon_i|X_i)=0
$$
implies that 
$$
\operatorname{Cov}(\epsilon_i,X_{ik})=0\quad \text{for all}\quad k=0,\dots,p,
$$
since
\begin{align*}
\operatorname{Cov}(\epsilon_i,X_{ik})
&=E(\epsilon_i X_{ik})- \overbrace{E(\epsilon_i)}^{=0}\; E(X_{ik})\\
&=E(\epsilon_i X_{ik})\\
&=E(E(\epsilon_i X_{ik}|X_i))\\
&=E(X_{ik} \; \underbrace{E(\epsilon_i |X_i)}_{=0}\,) = 0\quad \text{for all}\quad k=0,\dots,p.
\end{align*}
Thus 
$$
\underbrace{E(\epsilon_i|X_i)=0}_{A} \Rightarrow \underbrace{\operatorname{Cov}(\epsilon_i,X_{ik})=0\quad \text{for all}\quad k=0,\dots,p}_{B}
$$

Remember: Any logical implication ($A$ implies $B$)
$$
A\Rightarrow B
$$ 
has a logically equivalent contrapositive (not $B$ implies not $A$): 
$$
\neg B\Rightarrow \neg A
$$ 
Therefore, we also have that
$$
\underbrace{\operatorname{Cov}(\epsilon_i,X_{ik})\neq 0\;\text{for at least one}\; k=0,\dots,p}_{\neg B} \Rightarrow \underbrace{E(\epsilon_i|X_i)\neq 0}_{\neg A}
$$
I.e., if any of the regressors $X_{ik}$, $k=0,\dots,p,$ correlates with the error term $\epsilon_i$, then the exogeneity assumption is violated. 
\end{answerlist}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{0}
%% \exname{Ex_Ch3_1}