\begin{question}
Consider the matrix 
$$
A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}.
$$
\begin{answerlist}
\item Determine $A^\top$. Is $A$ symmetric?
\item Is $A$ idempotent?
\item Compute the determinant and the rank. Is $A$ nonsingular?
\item Compute the inverse.
\item Compute the trace.
\end{answerlist}
\end{question}

\begin{solution}
\begin{answerlist}
\item The transpose of $A$ is
$$
A^\top = \begin{pmatrix} 
1 & 3 \\ 
2 & 4 \end{pmatrix}.
$$
No, matrix $A$ is not symmetric, since $A\neq A^\top$.
\item No, matrix $A$ is not idempotent, since 
$$
AA = 
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} 
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} = 
\begin{pmatrix} 7 & 10 \\ 15 & 22 \end{pmatrix} \neq A.
$$
\item Remember: $\operatorname{det}\begin{pmatrix} a & b \\ c & d \end{pmatrix}=ad-bc$. 
The determinant of $A$ is 
$$
\operatorname{det}(A) 
= \operatorname{det}\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} 
= 1\cdot 4 - 2\cdot 3 = 4 - 6 = -2.
$$
Since $\operatorname{det}(A) \neq 0$, matrix $A$ 
\begin{itemize}
\item has full rank and 
\item is nonsingular.
\end{itemize}
\item Since $A$ has full rank (and is nonsingular), the inverse of $A$ exists and is given by
$$
A^{-1} = \frac{1}{\operatorname{det}(A)} \begin{pmatrix} 4 & -2 \\ -3 & 1 \end{pmatrix} = -\frac{1}{2} \begin{pmatrix} 4 & -2 \\ -3 & 1 \end{pmatrix} = \begin{pmatrix} -2 & 1 \\ 3/2 & -1/2 \end{pmatrix}.
$$
\item The trace of a matrix is the sum of the diagonal elements. For matrix $A$ we have
$$
\operatorname{tr}(A) = 1 + 4 = 5.
$$
\end{answerlist}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{0}
%% \exname{Ex_Ch3_1}