<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>4&nbsp; Multiple Linear Regression – Statistical Learning for Business and Economics (B.Sc.)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_ExtendingLinearRegression.html" rel="next">
<link href="./Ch_SimpleLinearRegression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_MultipleLinearRegression.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/KU_Logo_Blau_M.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Learning for Business and Economics (B.Sc.)</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Organization of the Course</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_Intro2R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_ReviewProbStats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Review of Probability and Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_SimpleLinearRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_MultipleLinearRegression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_ExtendingLinearRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Extending and Evaluating the Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_NonParamRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Nonparametric Regression and Cross-Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch5_Classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch6_Bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_MatrixAlgebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Matrix Algebra</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-multipleLinReg" id="toc-sec-multipleLinReg" class="nav-link active" data-scroll-target="#sec-multipleLinReg"><span class="header-section-number">4.1</span> Multiple Linear Regression</a>
  <ul class="collapse">
<li><a href="#sec-OVB" id="toc-sec-OVB" class="nav-link" data-scroll-target="#sec-OVB"><span class="header-section-number">4.1.1</span> Why Simple Regression Is Not Enough: Omitted Variable Bias</a></li>
  <li><a href="#sec-multipleLR-model" id="toc-sec-multipleLR-model" class="nav-link" data-scroll-target="#sec-multipleLR-model"><span class="header-section-number">4.1.2</span> The Multiple Linear Regression Model</a></li>
  <li><a href="#sec-OLS-multiple" id="toc-sec-OLS-multiple" class="nav-link" data-scroll-target="#sec-OLS-multiple"><span class="header-section-number">4.1.3</span> OLS Estimation</a></li>
  <li><a href="#sec-robustSE" id="toc-sec-robustSE" class="nav-link" data-scroll-target="#sec-robustSE"><span class="header-section-number">4.1.4</span> Properties and Robust Standard Errors</a></li>
  <li><a href="#sec-multipleLR-inference" id="toc-sec-multipleLR-inference" class="nav-link" data-scroll-target="#sec-multipleLR-inference"><span class="header-section-number">4.1.5</span> Statistical Inference</a></li>
  <li><a href="#sec-genderGap" id="toc-sec-genderGap" class="nav-link" data-scroll-target="#sec-genderGap"><span class="header-section-number">4.1.6</span> A Binary Predictor: The Gender Wage Gap</a></li>
  <li><a href="#sec-interactions" id="toc-sec-interactions" class="nav-link" data-scroll-target="#sec-interactions"><span class="header-section-number">4.1.7</span> Interaction Effects: Do Returns to Education Differ by Gender?</a></li>
  </ul>
</li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-multipleLinRegCh" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- LTeX: language=en-US --><p>We continue with the <code>wage1</code> data from <a href="Ch_SimpleLinearRegression.html" class="quarto-xref"><span>Chapter 3</span></a>. Since each chapter’s R code runs in its own fresh session, we reload the data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://justinmshea.github.io/wooldridge/">"wooldridge"</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"wage1"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="sec-multipleLinReg" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="sec-multipleLinReg">
<span class="header-section-number">4.1</span> Multiple Linear Regression</h2>
<p>Education alone leaves much of the variation in wages unexplained: <a href="Ch_SimpleLinearRegression.html#fig-wage-educ" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> shows that workers with the same education earn very different wages. Other factors (work experience, job tenure, gender) clearly matter. Adding them simultaneously serves two goals:</p>
<ol type="1">
<li>it improves prediction accuracy (see <a href="Ch_ExtendingLinearRegression.html#sec-model-fit" class="quarto-xref"><span>Section 5.3.1</span></a>)</li>
<li>it can correct for bias in the parameter estimate of the education effect (see next chapter)</li>
</ol>
<section id="sec-OVB" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="sec-OVB">
<span class="header-section-number">4.1.1</span> Why Simple Regression Is Not Enough: Omitted Variable Bias</h3>
<p>Compare the OLS estimate of the education coefficient in two models:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_simple</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span>,         data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="va">lm_educ_exper</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span>, data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span></span>
<span>  simple   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_simple</span><span class="op">)</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span>,</span>
<span>  multiple <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_educ_exper</span><span class="op">)</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              educ
simple   0.5413593
multiple 0.6442721</code></pre>
</div>
</div>
<p>The coefficient on <code>educ</code> changes when we add <code>exper</code>. This is not a coincidence — it is <strong>omitted variable bias (OVB)</strong>.</p>
<section id="the-ovb-formula" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="the-ovb-formula"><strong>The OVB Formula</strong></h4>
<p>Suppose the true model contains two predictors: <span id="eq-true-model"><span class="math display">\[
Y_i = \beta_1 + \beta_2 X_{i2} + \beta_3 X_{i3} + \varepsilon_i,
\qquad(4.1)\]</span></span> with strictly exogenous predictors (Assumption 2) <span class="math inline">\(X=(1,X_{12},\dots,X_{n2},X_{13},\dots,X_{n3})\)</span> <span class="math display">\[
E(\varepsilon_i \mid X) = 0\quad\text{for all}\quad i=1,\dots,n.
\]</span></p>
<p><strong>Parameter of interest.</strong> Say the parameter of interest is <span class="math inline">\(\beta_2\)</span> — the marginal effect of <span class="math inline">\(X_2\)</span> on the outcome <span class="math inline">\(Y_i.\)</span></p>
<p><strong>Estimating a misspecified model.</strong> Suppose we guess wrong and leave out <span class="math inline">\(X_{i3}.\)</span> Instead of the true model (<a href="#eq-true-model" class="quarto-xref">Equation&nbsp;<span>4.1</span></a>), we estimate the <strong>misspecified</strong> simple regression model <span class="math display">\[
Y_i = \gamma_1 + \gamma_2 X_{i2} + u_i.
\]</span> This violates Assumption 1: we are fitting the wrong (false) linear model.</p>
<p>The crucial question: is the estimator <span class="math display">\[
\widehat\gamma_2
= \frac{\displaystyle\frac{1}{n}\sum_{i=1}^{n}(X_{i2} - \bar X_2)(Y_{i} - \bar Y)}
       {\displaystyle\frac{1}{n}\sum_{i=1}^{n}(X_{i2} - \bar X_2)^2}
= \frac{\widehat{\operatorname{Cov}}(X_2,\,Y)}{\widehat{\operatorname{Var}}(X_2)}
\]</span> still a reliable estimator of <span class="math inline">\(\beta_2\)</span>?</p>
<p>After all, we only left out <span class="math inline">\(X_{i3}\)</span> — and we don’t even care about its effect. The predictor we do care about, <span class="math inline">\(X_{i2},\)</span> is still in the model. So, what could possibly go wrong?!</p>
<p><strong>The sample decomposition.</strong> The estimator <span class="math inline">\(\widehat\gamma_2\)</span> decomposes into the multiple-regression slope <span class="math inline">\(\widehat\beta_2\)</span> plus an empirical <strong>bias term</strong>: <span id="eq-OVB-sample"><span class="math display">\[
\widehat{\gamma}_2 = \widehat{\beta}_2 + \underbrace{\widehat{\beta}_3 \cdot \widehat\delta}_{\text{empirical bias}},
\qquad(4.2)\]</span></span> where:</p>
<ul>
<li>
<span class="math inline">\(\widehat\beta_2\)</span> and <span class="math inline">\(\widehat\beta_3\)</span> are the OLS estimators from the true multiple regression (<a href="#eq-true-model" class="quarto-xref">Equation&nbsp;<span>4.1</span></a>), and</li>
<li>
<span class="math inline">\(\widehat\delta\)</span> is the OLS slope of the auxiliary regression <span class="math inline">\(X_{i3} = \alpha + \delta X_{i2} + e_i,\)</span> i.e.&nbsp;regressing the omitted predictor <span class="math inline">\(X_{i3}\)</span> on the included predictor <span class="math inline">\(X_{i2}\colon\)</span> <span id="eq-OVB-delta"><span class="math display">\[
\widehat\delta
= \frac{\displaystyle\frac{1}{n}\sum_{i=1}^{n}(X_{i2} - \bar X_2)(X_{i3} - \bar X_3)}
     {\displaystyle\frac{1}{n}\sum_{i=1}^{n}(X_{i2} - \bar X_2)^2}
= \frac{\widehat{\operatorname{Cov}}(X_2,\,X_3)}{\widehat{\operatorname{Var}}(X_2)}.
\qquad(4.3)\]</span></span>
</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: Derivation of the Sample Decomposition <a href="#eq-OVB-sample" class="quarto-xref">Equation&nbsp;<span>4.2</span></a>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Start from the definition of <span class="math inline">\(\widehat\gamma_2,\)</span> and substitute <span class="math inline">\(Y_i\)</span>.</strong> <span class="math display">\[
\widehat\gamma_2 = \frac{\widehat{\operatorname{Cov}}(X_2,\,Y)}{\widehat{\operatorname{Var}}(X_2)}.
\]</span> The fitted values of the multiple regression satisfy <span class="math display">\[
Y_i = \widehat\beta_1 + \widehat\beta_2 X_{i2} + \widehat\beta_3 X_{i3} + \widehat\varepsilon_i.
\]</span> <strong>Step 2: Expand the covariance.</strong> Plugging this in for <span class="math inline">\(Y\)</span> and using the linearity of the (sample) covariance, <span class="math display">\[\begin{align*}
\widehat\gamma_2
&amp;= \frac{\widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\beta_1 + \widehat\beta_2 X_2 + \widehat\beta_3 X_3 + \widehat\varepsilon\bigr)}{\widehat{\operatorname{Var}}(X_2)}\\[2ex]
&amp;\text{using the linearity of the sample covariance:}\\[2ex]
&amp;= \frac{
  \widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\beta_1\bigr) +
  \widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\beta_2 X_2\bigr) +
  \widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\beta_3 X_3\bigr) +
  \widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\varepsilon\bigr)}{\widehat{\operatorname{Var}}(X_2)}\\[2ex]
&amp;\text{factoring out factors that do not vary accross $i=1,\dots,n\colon$}\\[2ex]  
&amp;= \frac{
  \widehat\beta_1 \,\widehat{\operatorname{Cov}}\bigl(X_2,\,1\bigr)+
  \widehat\beta_2 \,\widehat{\operatorname{Cov}}\bigl(X_2,\,X_2\bigr) +
  \widehat\beta_3 \,\widehat{\operatorname{Cov}}\bigl(X_2,\,X_3\bigr) +
  \widehat{\operatorname{Cov}}\bigl(X_2,\,\widehat\varepsilon\bigr)}{\widehat{\operatorname{Var}}(X_2)}\\[2ex]  
&amp;= \frac{0+\widehat\beta_2\,\widehat{\operatorname{Var}}(X_2) + \widehat\beta_3\,\widehat{\operatorname{Cov}}(X_2,\,X_3) + 0}{\widehat{\operatorname{Var}}(X_2)}
\end{align*}\]</span> using that:</p>
<ul>
<li><span class="math inline">\(\widehat{\operatorname{Cov}}(X_2,\, 1) = 0\)</span></li>
<li>
<span class="math inline">\(\widehat{\operatorname{Cov}}(X_2,X_2) = \widehat{\operatorname{Var}}(X_2)\)</span>.</li>
<li>
<span class="math inline">\(\widehat{\operatorname{Cov}}(X_2,\,\widehat\varepsilon)=0,\)</span> since by the orthogonal projection property of OLS: <span class="math display">\[\begin{align*}
\widehat{\operatorname{Cov}}(X_2,\,\widehat\varepsilon)
&amp; = \frac{1}{n}\sum_{i=1}^n (X_{i2}-\bar X_2)\,\widehat\varepsilon_i\\[2ex]
&amp; = \frac{1}{n}\Bigl(\underbrace{\textstyle\sum_{i=1}^n X_{i2}\widehat\varepsilon_i}_{=0} - \bar X_2\underbrace{\textstyle\sum_{i=1}^n \widehat\varepsilon_i}_{=0}\Bigr)\\[2ex]
&amp; = 0.
\end{align*}\]</span>
</li>
</ul>
<p><strong>Step 3: Simplify.</strong></p>
<p><span class="math display">\[\begin{align*}
\widehat\gamma_2
&amp;= \frac{0+\widehat\beta_2\,\widehat{\operatorname{Var}}(X_2) + \widehat\beta_3\,\widehat{\operatorname{Cov}}(X_2,\,X_3) + 0}{\widehat{\operatorname{Var}}(X_2)}\\[2ex]
&amp;= \widehat\beta_2 + \widehat\beta_3\, \underbrace{\frac{\widehat{\operatorname{Cov}}(X_2,\,X_3)}{\widehat{\operatorname{Var}}(X_2)}}_{=\widehat{\delta}}.
\end{align*}\]</span></p>
<p>That is, the estimator <span class="math inline">\(\widehat{\gamma}_2\)</span> equals the estimator <span class="math inline">\(\widehat{\beta}_2\)</span> plus a potential bias term <span class="math inline">\(\widehat\beta_3\,\widehat{\delta}.\)</span></p>
</div>
</div>
</div>
<p>That is: <span class="math inline">\(\widehat{\gamma}_2\)</span> (misspecified model) and <span class="math inline">\(\widehat{\beta}_2\)</span> (true model) are connected — but with a potential empirical <strong>bias term</strong> <span class="math inline">\(\widehat{\beta}_3\,\widehat{\delta}\)</span> attached.</p>
<p>In our <code>wage1</code> data, the sample decomposition <a href="#eq-OVB-sample" class="quarto-xref">Equation&nbsp;<span>4.2</span></a> is given by: <span class="math display">\[
\underbrace{0.541}_{\widehat\gamma_2}
= \underbrace{0.644}_{\widehat\beta_2}
+ \underbrace{0.070}_{\widehat\beta_3}
\cdot \underbrace{(-1.468)}_{\widehat\delta}.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code to Reproduce the Omitted Variable Bias Decomposition
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## delta_hat = sample covariance / sample variance (formula above)</span></span>
<span><span class="va">delta_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">educ</span>, <span class="va">wage1</span><span class="op">$</span><span class="va">exper</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">educ</span><span class="op">)</span></span>
<span></span>
<span><span class="va">beta3_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_educ_exper</span><span class="op">)</span><span class="op">[</span><span class="st">"exper"</span><span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>delta_hat    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">delta_hat</span><span class="op">)</span>,</span>
<span>  beta3_hat    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">beta3_hat</span><span class="op">)</span>,</span>
<span>  bias         <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">beta3_hat</span> <span class="op">*</span> <span class="va">delta_hat</span><span class="op">)</span>,</span>
<span>  educ_2_mult  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_educ_exper</span><span class="op">)</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>  educ_2_mult_p_bias <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_educ_exper</span><span class="op">)</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span> <span class="op">+</span> <span class="va">beta3_hat</span> <span class="op">*</span> <span class="va">delta_hat</span><span class="op">)</span>,</span>
<span>  educ_2_simple <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_simple</span><span class="op">)</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         delta_hat          beta3_hat               bias        educ_2_mult 
        -1.4681823          0.0700954         -0.1029128          0.6442721 
educ_2_mult_p_bias      educ_2_simple 
         0.5413593          0.5413593 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>However, a single realization of <span class="math inline">\(\widehat{\gamma}_2\)</span> cannot tell us whether it is a reliable estimator of <span class="math inline">\(\beta_2.\)</span></p>
<p>We call <span class="math inline">\(\widehat{\gamma}_2\)</span> a reliable estimator of <span class="math inline">\(\beta_2\)</span> if it is <strong>unbiased</strong> — i.e., if its <strong>expected value</strong> equals <span class="math inline">\(\beta_2\)</span>: <span class="math display">\[\begin{align*}
E(\widehat{\gamma}_2\mid X) &amp; \neq \beta_2\quad \text{biased, unreliable estimator}\\[2ex]
E(\widehat{\gamma}_2\mid X) &amp; = \beta_2\quad \text{unbiased, reliable estimator}
\end{align*}\]</span></p>
<p>It turns out that, in general, the conditional mean of <span class="math inline">\(\widehat{\gamma}_2\)</span> given <span class="math inline">\(X = (X_{12}, \dots, X_{n2},\; X_{13}, \dots, X_{n3})\)</span> is <strong>not</strong> equal to <span class="math inline">\(\beta_2\)</span>: <span id="eq-OVB"><span class="math display">\[
E(\widehat\gamma_2 \mid X) = \beta_2 + \underbrace{\beta_3 \cdot \widehat\delta}_{\text{bias}},
\qquad(4.4)\]</span></span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: Derivation of the OVB Formula <a href="#eq-OVB" class="quarto-xref">Equation&nbsp;<span>4.4</span></a>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Take the conditional expectation of the sample decomposition <a href="#eq-OVB-sample" class="quarto-xref">Equation&nbsp;<span>4.2</span></a>.</strong> Since <span class="math inline">\(\widehat\delta\)</span> depends only on the predictor values <span class="math inline">\(X_{i2}, X_{i3}\)</span> (and is hence non-random given <span class="math inline">\(X\)</span>), <span class="math display">\[\begin{align*}
E(\widehat\gamma_2 \mid X)
&amp;= E\bigl(\widehat\beta_2 + \widehat\beta_3\,\widehat\delta \mid X\bigr)\\[2ex]
&amp;= E(\widehat\beta_2\mid X) + E(\widehat\beta_3\mid X)\,\widehat\delta.
\end{align*}\]</span></p>
<p>Because the <strong>true</strong> model <a href="#eq-true-model" class="quarto-xref">Equation&nbsp;<span>4.1</span></a> satisfies strict exogeneity, <span class="math inline">\(E(\varepsilon_i\mid X)=0\)</span>, the multiple-regression OLS estimators <span class="math inline">\(\widehat\beta_2\)</span> and <span class="math inline">\(\widehat\beta_3\)</span> are unbiased for the true <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\beta_3\)</span> — exactly as in <a href="Ch_SimpleLinearRegression.html#sec-simpleLR-props" class="quarto-xref"><span>Section 3.2.4</span></a>, now with two predictors instead of one (proven in general in <a href="#sec-OLS-multiple" class="quarto-xref"><span>Section 4.1.3</span></a>): <span class="math display">\[
E(\widehat\beta_2\mid X) = \beta_2
\qquad\text{and}\qquad
E(\widehat\beta_3\mid X) = \beta_3.
\]</span></p>
<p>Plugging this in gives <a href="#eq-OVB" class="quarto-xref">Equation&nbsp;<span>4.4</span></a>: <span class="math display">\[
E(\widehat\gamma_2 \mid X) = \beta_2 + \beta_3\,\widehat\delta. \qquad \blacksquare
\]</span></p>
</div>
</div>
</div>
<p>The bias is non-zero whenever</p>
<div class="spaced-list">
<ol type="1">
<li>
<span class="math inline">\(\beta_3 \neq 0\)</span>: the omitted variable affects <span class="math inline">\(Y\)</span>, and</li>
<li>
<span class="math inline">\(\widehat\delta \neq 0\)</span>: the omitted variable is correlated with the included predictor <span class="math inline">\(X_{i2}\)</span> in the sample, <span class="math display">\[
\widehat{\operatorname{Cov}}(X_2,\,X_3) \neq 0.
\]</span>
</li>
</ol>
</div>
<p>In the wages example, with</p>
<ul>
<li><span class="math inline">\(X_{i2} = \text{educ}_i\)</span></li>
<li>
<span class="math inline">\(X_{i3} = \text{exper}_i\)</span>,</li>
</ul>
<p>we have:</p>
<div class="spaced-list">
<ol type="1">
<li>Experience raises wages, thus <span class="math inline">\(\beta_3 &gt; 0.\)</span>
</li>
<li>Workers who spent more years in school have fewer years of work experience, so <span class="math inline">\(\widehat{\operatorname{Cov}}(X_2,\,X_3)&lt;0\)</span> and thus <span class="math inline">\(\widehat\delta &lt; 0\)</span>.</li>
</ol>
</div>
<p>Thus, we expect <span class="math inline">\(\widehat\gamma_2\)</span> to be negatively biased for <span class="math inline">\(\beta_2\)</span>: <span class="math display">\[
E(\widehat\gamma_2 \mid X) = \beta_2 + \underbrace{\beta_3 \cdot \widehat\delta}_{&lt;0}.
\]</span> The misspecified estimator <span class="math inline">\(\widehat\gamma_2\)</span> will systematically <strong>understate</strong> the true return to education, <span class="math inline">\(\beta_2.\)</span> Omitting the experience variable <span class="math inline">\(X_{i3}=\)</span><code>exper</code><span class="math inline">\(_i\)</span> is therefore a fundamental problem for estimating <span class="math inline">\(\beta_2.\)</span></p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Business Takeaway: Which Variables Are in the Model Matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>The estimated education coefficient moved from 0.54 to 0.64 just by adding experience. Whenever someone presents a regression result (a consultant, a colleague, a dashboard, etc) ask:</p>
<p>“What else could drive both the predictor of interest (e.g.&nbsp;<span class="math inline">\(X_{i2}\)</span>) and the outcome <span class="math inline">\(Y_i\)</span>, and is it in the model?”</p>
</div>
</div>
<div class="callout callout-style-simple callout-caution">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>OVB is a <strong>causal</strong> problem, not a mechanical one. Including additional control variables reduces bias only if those variables are themselves exogenous. Adding a “bad control”, i.e., a variable that is affected by <span class="math inline">\(X_{i2},\)</span> can introduce new bias. We return to this in <a href="Ch_ExtendingLinearRegression.html#sec-whatdoesbeta" class="quarto-xref"><span>Section 5.4</span></a>.</p>
</div>
</div>
</div>
</section></section><section id="sec-multipleLR-model" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="sec-multipleLR-model">
<span class="header-section-number">4.1.2</span> The Multiple Linear Regression Model</h3>
<p>The <strong>multiple linear regression model</strong> with <span class="math inline">\(K\)</span> parameters (an intercept and <span class="math inline">\(K-1\)</span> predictors) is</p>
<p><span id="eq-multipleLR"><span class="math display">\[
Y_i = \beta_1 + \beta_2 X_{i2} + \dots + \beta_K X_{iK} + \varepsilon_i,
  \quad i = 1, \dots, n.
\qquad(4.5)\]</span></span></p>
<p>For instance, the model with education, experience, and tenure has <span class="math inline">\(K = 4\)</span> parameters:</p>
<p><span class="math display">\[
\text{wage}_i = \beta_1 + \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i
              + \beta_4\,\text{tenure}_i + \varepsilon_i.
\]</span></p>
<p>The <strong>multiple linear regression model</strong> <a href="#eq-multipleLR" class="quarto-xref">Equation&nbsp;<span>4.5</span></a> specifies the conditional mean of <span class="math inline">\(Y_i\)</span> given <span class="math inline">\(X_{i2} = x_2, \dots, X_{iK} = x_K\)</span> as a linear function <span class="math display">\[\begin{align*}
&amp;m(x_2, \dots, x_K)\\[2ex]
&amp; = E(Y_i \mid X_{i2} = x_2, \dots, X_{iK} = x_K) \\[2ex]
&amp; = E(\beta_1 + \beta_2 X_{i2} + \dots + \beta_K X_{iK} + \varepsilon_i \mid X_{i2} = x_2, \dots, X_{iK} = x_K) \\[2ex]
&amp; = \beta_1 + \beta_2 x_2 + \dots + \beta_K x_K
    + \underbrace{E(\varepsilon_i \mid X_{i2} = x_2, \dots, X_{iK} = x_K)}_{=0} \\[2ex]
&amp; = \beta_1 + \beta_2 x_2 + \dots + \beta_K x_K,
\end{align*}\]</span> where the error term drops out by (strict) exogeneity; see the assumptions below.</p>
<p><strong>Interpretation of <span class="math inline">\(\beta_k\)</span>.</strong> Each slope <span class="math inline">\(\beta_k\)</span>, <span class="math inline">\(k = 2, \dots, K\)</span>, equals the partial derivative of the conditional mean function <span class="math inline">\(m(x_2, \dots, x_K)\)</span> with respect to <span class="math inline">\(x_k\)</span>:</p>
<p><span class="math display">\[\begin{align*}
&amp;\frac{\partial}{\partial x_k} m(x_2, \dots, x_K)\\[2ex]
&amp; = \frac{\partial}{\partial x_k} E(Y_i \mid X_{i2} = x_2, \dots, X_{iK} = x_K) \\[2ex]
&amp; = \frac{\partial}{\partial x_k} \left(\beta_1 + \beta_2 x_2 + \dots + \beta_k x_k + \dots + \beta_K x_K\right) \\[2ex]
&amp; = \beta_k.
\end{align*}\]</span></p>
<p>In words: a one-unit increase in <span class="math inline">\(X_{ik}\)</span> changes the <em>expected</em> value of <span class="math inline">\(Y_i\)</span> by <span class="math inline">\(\beta_k\)</span> units, <em>holding all other predictors constant</em>. That is why <span class="math inline">\(\beta_k\)</span> is called a <strong>partial effect</strong>. In the wages example with education, experience, and tenure, <span class="math inline">\(\beta_2\)</span> measures the expected wage premium per additional year of schooling, in dollars per hour, for workers with the <em>same</em> experience and tenure.</p>
<p>The OLS estimator <span class="math inline">\(\widehat\beta = (\widehat\beta_1, \dots, \widehat\beta_K)\)</span> has desirable statistical properties under four assumptions.</p>
<section id="assumption-1-linear-model-and-random-sampling" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-1-linear-model-and-random-sampling"><strong>Assumption 1: Linear Model and Random Sampling</strong></h4>
<p>The data <span class="math inline">\((Y_1, X_{12}, \dots, X_{1K}), \dots, (Y_n, X_{n2}, \dots, X_{nK})\)</span> are a realization of an <strong>(i.i.d.) random sample</strong> from the multiple linear regression model <a href="#eq-multipleLR" class="quarto-xref">Equation&nbsp;<span>4.5</span></a>.</p>
</section><section id="assumption-2-strict-exogeneity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-2-strict-exogeneity"><strong>Assumption 2: Strict Exogeneity</strong></h4>
<p><span class="math display">\[
E(\varepsilon_i \mid X) = 0, \quad i = 1, \dots, n,
\]</span> where <span class="math inline">\(X=(X_{12},\dots,X_{nK})\)</span> contains all predictor values <span class="math inline">\(X_{i2}, \dots, X_{iK}\)</span> of all workers <span class="math inline">\(i = 1, \dots, n\)</span>. Worker <span class="math inline">\(i\)</span>’s error <span class="math inline">\(\varepsilon_i\)</span> has mean zero regardless of <em>everyone’s</em> predictor values — not only worker <span class="math inline">\(i\)</span>’s own.</p>
</section><section id="assumption-3-no-perfect-multicollinearity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-3-no-perfect-multicollinearity"><strong>Assumption 3: No Perfect Multicollinearity</strong></h4>
<p><span class="math display">\[
\operatorname{rank}(X) = K.
\]</span></p>
<p>No predictor may be an exact linear combination of the other predictors (including the intercept) — otherwise the columns of <span class="math inline">\(X\)</span> are linearly dependent, <span class="math inline">\(\operatorname{rank}(X) &lt; K\)</span>, and the estimator <span class="math inline">\(\widehat\beta\)</span> is not uniquely defined. For example, we cannot include both a dummy <code>female</code> and a dummy <code>male</code> $= 1 - $<code>female</code> together with an intercept — the data could not tell their effects apart.</p>
</section><section id="assumption-4-homoskedasticity" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="assumption-4-homoskedasticity"><strong>Assumption 4: Homoskedasticity</strong></h4>
<p><span class="math display">\[
\operatorname{Var}(\varepsilon_i \mid X) = \sigma^2 \quad\text{for all}\quad i = 1, \dots, n.
\]</span></p>
<p>The variance of the error is constant across all predictor values.</p>
</section></section><section id="sec-OLS-multiple" class="level3" data-number="4.1.3"><h3 data-number="4.1.3" class="anchored" data-anchor-id="sec-OLS-multiple">
<span class="header-section-number">4.1.3</span> OLS Estimation</h3>
<p>The <strong>OLS estimator</strong> chooses <span class="math inline">\(\widehat\beta_1, \dots, \widehat\beta_K\)</span> to minimize the sum of squared deviations</p>
<p><span id="eq-OLS-multiple"><span class="math display">\[
(\widehat\beta_1, \dots, \widehat\beta_K)
= \arg\min_{b_1, \dots, b_K}
  \sum_{i=1}^{n} \bigl(Y_i - b_1 - b_2 X_{i2} - \dots - b_K X_{iK}\bigr)^2.
\qquad(4.6)\]</span></span></p>
<p>With several predictors, there is no longer a short formula like <a href="Ch_SimpleLinearRegression.html#eq-OLS-slope" class="quarto-xref">Equation&nbsp;<span>3.3</span></a> that one would compute by hand. <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> solves the minimization problem for us:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_multiple</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span> <span class="op">+</span> <span class="va">tenure</span>, data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_multiple</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        educ       exper      tenure 
-2.87273482  0.59896507  0.02233952  0.16926865 </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> Controlling for experience and tenure, each additional year of education is associated with approximately 0.6 dollars/hour higher wages.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Business Takeaway: Reading a Coefficient
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Controlling for experience and tenure” means <em>comparing workers who are alike in these respects</em>. An HR analyst can report: “Among employees with the same experience and tenure, those with one more year of education earn on average $0.60 more per hour.”</p>
<p>❗ The coefficient does <em>not</em> say that paying for an employee’s extra year of schooling will raise their wage by this amount — that is a causal claim, which we examine in <a href="Ch_ExtendingLinearRegression.html#sec-whatdoesbeta" class="quarto-xref"><span>Section 5.4</span></a>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: OLS in Matrix Form
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This box requires matrix algebra; see <a href="Ch_MatrixAlgebra.html" class="quarto-xref"><span>Appendix A</span></a> for a refresher.</p>
<p>Set <span class="math inline">\(X_{i1} = 1\)</span> for the intercept and stack all <span class="math inline">\(n\)</span> observations:</p>
<p><span class="math display">\[
\underset{(n\times 1)}{Y}
= \underset{(n\times K)}{X}\;
  \underset{(K\times 1)}{\beta}
+ \underset{(n\times 1)}{\varepsilon},
\]</span> <span class="math display">\[
Y = \begin{pmatrix}Y_1\\\vdots\\Y_n\end{pmatrix},\;
X = \begin{pmatrix}
  1 &amp; X_{12} &amp; \cdots &amp; X_{1K}\\
  \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
  1 &amp; X_{n2} &amp; \cdots &amp; X_{nK}
\end{pmatrix},\;
\beta = \begin{pmatrix}\beta_1\\\vdots\\\beta_K\end{pmatrix}.
\]</span></p>
<p>The sum of squares in <a href="#eq-OLS-multiple" class="quarto-xref">Equation&nbsp;<span>4.6</span></a> becomes <span class="math display">\[
\widehat\beta = \begin{pmatrix}
\widehat\beta_1\\\vdots\\\widehat\beta_K
\end{pmatrix}
= \arg\min_{b\in\mathbb{R}^K}(Y - Xb)^\top(Y - Xb).
\]</span></p>
<p>Setting its gradient to zero gives the <strong>normal equations</strong> <span class="math display">\[
X^\top X\,\widehat\beta = X^\top Y.
\]</span> No perfect multicollinearity means <span class="math display">\[
\operatorname{rank}(X) = K,
\]</span> so the <span class="math inline">\((K\times K)\)</span>-matrix <span class="math display">\[
X^\top X
\]</span> is invertible and <span id="eq-OLS-matrix"><span class="math display">\[
\widehat\beta = (X^\top X)^{-1} X^\top Y.
\qquad(4.7)\]</span></span></p>
<p>The fitted values are <span class="math display">\[
\widehat Y = X\widehat\beta = HY
\]</span> with the <span class="math inline">\((n \times n)\)</span> <strong>projection matrix</strong> (hat matrix) <span class="math display">\[
H = X(X^\top X)^{-1}X^\top.
\]</span> Its diagonal elements <span class="math inline">\(h_{ii}\)</span> are <strong>leverage statistics</strong>: a large <span class="math inline">\(h_{ii}\)</span> means observation <span class="math inline">\(i\)</span> has unusual predictor values and thus a potentially large influence on <span class="math inline">\(\widehat\beta.\)</span></p>
<p>We can verify <a href="#eq-OLS-matrix" class="quarto-xref">Equation&nbsp;<span>4.7</span></a> in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">X</span>        <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="va">lm_multiple</span><span class="op">)</span></span>
<span><span class="va">Y</span>        <span class="op">&lt;-</span> <span class="va">wage1</span><span class="op">$</span><span class="va">wage</span></span>
<span><span class="va">beta_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">Y</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>beta_by_hand <span class="op">=</span> <span class="va">beta_hat</span>, </span>
<span>            beta_by_R    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_multiple</span><span class="op">)</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    beta_by_R
(Intercept) -2.8727   -2.8727
educ         0.5990    0.5990
exper        0.0223    0.0223
tenure       0.1693    0.1693</code></pre>
</div>
</div>
<p>Under Assumptions 1–4, <span class="math inline">\(\operatorname{Var}(\widehat\beta \mid X) = \sigma^2 (X^\top X)^{-1}\)</span>; the standard errors reported by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> are the square roots of the diagonal elements of <span class="math display">\[
\widehat\sigma^2 (X^\top X)^{-1}.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Proof: <span class="math inline">\(\operatorname{Var}(\widehat\beta \mid X) = \sigma^2 (X^\top X)^{-1}\)</span>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Write <span class="math inline">\(\widehat\beta\)</span> in terms of the errors.</strong> By the rank condition, <span class="math inline">\(X^\top X\)</span> is invertible. Plugging the model <span class="math inline">\(Y = X\beta + \varepsilon\)</span> (Assumption 1) into <a href="#eq-OLS-matrix" class="quarto-xref">Equation&nbsp;<span>4.7</span></a> gives <span class="math display">\[\begin{align*}
\widehat\beta
&amp; = (X^\top X)^{-1} X^\top (X\beta + \varepsilon) \\[2ex]
&amp; = \underbrace{(X^\top X)^{-1} X^\top X}_{= I_K}\,\beta + (X^\top X)^{-1} X^\top \varepsilon \\[2ex]
&amp; = \beta + (X^\top X)^{-1} X^\top \varepsilon.
\end{align*}\]</span></p>
<p><strong>Step 2: The conditional mean.</strong> Given <span class="math inline">\(X\)</span>, the matrix <span class="math inline">\((X^\top X)^{-1} X^\top\)</span> is fixed, so by strict exogeneity (Assumption 2), <span class="math inline">\(E(\varepsilon \mid X) = 0\)</span>, <span class="math display">\[
E(\widehat\beta \mid X) = \beta + (X^\top X)^{-1} X^\top E(\varepsilon \mid X) = \beta.
\]</span> (This also proves that the OLS estimators are unbiased.)</p>
<p><strong>Step 3: The conditional variance.</strong> By definition and Steps 1–2, <span class="math display">\[\begin{align*}
\operatorname{Var}(\widehat\beta \mid X)
&amp; = E\bigl[(\widehat\beta - \beta)(\widehat\beta - \beta)^\top \mid X\bigr] \\[2ex]
&amp; = E\bigl[(X^\top X)^{-1} X^\top \varepsilon\,\varepsilon^\top X (X^\top X)^{-1} \mid X\bigr] \\[2ex]
&amp; = (X^\top X)^{-1} X^\top \, E(\varepsilon\,\varepsilon^\top \mid X) \, X (X^\top X)^{-1}.
\end{align*}\]</span> In the second line we used <span class="math inline">\(\bigl((X^\top X)^{-1} X^\top \varepsilon\bigr)^\top = \varepsilon^\top X (X^\top X)^{-1}\)</span>, since <span class="math inline">\(X^\top X\)</span> is symmetric.</p>
<p><strong>Step 4: The <span class="math inline">\((n \times n)\)</span> matrix <span class="math inline">\(E(\varepsilon\,\varepsilon^\top \mid X)\)</span>.</strong> Its elements are <span class="math inline">\(E(\varepsilon_i \varepsilon_j \mid X)\)</span>.</p>
<ul>
<li>
<em>Diagonal</em> (<span class="math inline">\(i = j\)</span>): since <span class="math inline">\(E(\varepsilon_i \mid X) = 0\)</span>, <span class="math inline">\(E(\varepsilon_i^2 \mid X) = \operatorname{Var}(\varepsilon_i \mid X) = \sigma^2\)</span> by homoskedasticity (Assumption 4).</li>
<li>
<em>Off-diagonal</em> (<span class="math inline">\(i \neq j\)</span>): under random sampling (Assumption 1), worker <span class="math inline">\(i\)</span>’s data are independent of worker <span class="math inline">\(j\)</span>’s data, so <span class="math inline">\(E(\varepsilon_i \varepsilon_j \mid X) = E(\varepsilon_i \mid X)\, E(\varepsilon_j \mid X) = 0 \cdot 0 = 0\)</span>.</li>
</ul>
<p>Hence <span class="math display">\[
E(\varepsilon\,\varepsilon^\top \mid X) = \sigma^2 I_n.
\]</span></p>
<p><strong>Step 5: Put everything together.</strong> Plugging Step 4 into Step 3, <span class="math display">\[\begin{align*}
\operatorname{Var}(\widehat\beta \mid X)
&amp; = (X^\top X)^{-1} X^\top \, \sigma^2 I_n \, X (X^\top X)^{-1} \\[2ex]
&amp; = \sigma^2 \, \underbrace{(X^\top X)^{-1} X^\top X}_{= I_K} \, (X^\top X)^{-1} \\[2ex]
&amp; = \sigma^2 (X^\top X)^{-1}. \qquad \blacksquare
\end{align*}\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="sec-robustSE" class="level3" data-number="4.1.4"><h3 data-number="4.1.4" class="anchored" data-anchor-id="sec-robustSE">
<span class="header-section-number">4.1.4</span> Properties and Robust Standard Errors</h3>
<p><strong>Unbiasedness.</strong> Under Assumptions 1–3, the OLS estimators are unbiased: <span class="math inline">\(E(\widehat\beta_k) = \beta_k\)</span> for every <span class="math inline">\(k = 1, \dots, K\)</span>.</p>
<p><strong>Standard errors.</strong> Under Assumptions 1–4, the variance-covariance matrix of <span class="math inline">\(\widehat\beta\)</span> is <span class="math inline">\(\sigma^2 (X^\top X)^{-1}\)</span> (see the box above). The standard errors reported by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> are the square roots of its diagonal elements, with the error variance estimated by <span class="math inline">\(\widehat\sigma^2 = \frac{1}{n-K}\sum_{i=1}^n\widehat\varepsilon_i^2\)</span>. These standard errors crucially rely on Assumption 4 (homoskedasticity). The scatter plot in <a href="Ch_SimpleLinearRegression.html#fig-wage-educ" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> suggests that this assumption is violated: the spread of wages increases with education.</p>
<p><strong>Heteroskedasticity.</strong> If the error variance <span class="math inline">\(\operatorname{Var}(\varepsilon_i \mid X) = \sigma_i^2\)</span> differs across workers, the homoskedastic formula <span class="math inline">\(\sigma^2 (X^\top X)^{-1}\)</span> no longer holds; the true variance takes the more general <strong>sandwich form</strong> given in the box below.</p>
<p>Using the homoskedastic standard errors although the errors are heteroskedastic leads to</p>
<ul>
<li>
<strong>wrong standard errors</strong>, and thus to</li>
<li>
<strong>wrong <span class="math inline">\(t\)</span>-statistics</strong>,</li>
<li>
<strong>wrong <span class="math inline">\(p\)</span>-values</strong>, and</li>
<li><strong>wrong confidence intervals</strong></li>
</ul>
<p>rendering inference unreliable.</p>
<p>Using heteroskedasticity-robust standard errors although the errors are actually homoskedastic is harmless: it still leads to (at least approximately, for large <span class="math inline">\(n\)</span>)</p>
<ul>
<li>
<strong>valid standard errors</strong>, and thus to</li>
<li>
<strong>valid <span class="math inline">\(t\)</span>-statistics</strong>,</li>
<li>
<strong>valid <span class="math inline">\(p\)</span>-values</strong>, and</li>
<li>
<strong>valid confidence intervals</strong>.</li>
</ul>
<p>The price is a <strong>loss of precision:</strong> robust standard errors are estimated less precisely than the usual ones, which matters mainly in small samples (smallish <span class="math inline">\(n\)</span>).</p>
<section id="heteroskedasticity-robust-standard-errors" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="heteroskedasticity-robust-standard-errors"><strong>Heteroskedasticity-Robust Standard Errors</strong></h4>
<p>The sandwich variance (box below) is not directly computable, since the <span class="math inline">\(\sigma_i^2\)</span> are unknown. Replacing each <span class="math inline">\(\sigma_i^2\)</span> by the squared residual <span class="math inline">\(\widehat\varepsilon_i^2\)</span> gives the so-called <strong>HC0</strong> heteroskedasticity-robust variance estimator. There are several refinements of this idea; the most commonly used, <strong>HC3</strong>, slightly inflates the squared residuals to improve small-sample behavior.</p>
<p>According to <span class="citation" data-cites="Long_Ervin_2000">Long and Ervin (<a href="#ref-Long_Ervin_2000" role="doc-biblioref">2000</a>)</span>, HC3 has the best finite-sample performance. The R packages <code>sandwich</code> and <code>lmtest</code> compute it for us:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://sandwich.R-Forge.R-project.org/">"sandwich"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"lmtest"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## HC3 heteroskedasticity-robust standard error</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">lm_multiple</span>, </span>
<span>         vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_multiple</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) -2.872735   0.819016 -3.5075 0.0004913 ***
educ         0.598965   0.061860  9.6826 &lt; 2.2e-16 ***
exper        0.022340   0.010663  2.0950 0.0366507 *  
tenure       0.169269   0.029854  5.6698 2.368e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>In applied work, <strong>always report HC3 robust standard errors</strong>. The coefficient estimates <span class="math inline">\(\widehat\beta_k\)</span> are unchanged; only standard errors, <span class="math inline">\(t\)</span>-statistics, and confidence intervals are affected.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: The Sandwich Formula
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This box requires matrix algebra; see <a href="Ch_MatrixAlgebra.html" class="quarto-xref"><span>Appendix A</span></a>.</p>
<p>In matrix notation (see the box in <a href="#sec-OLS-multiple" class="quarto-xref"><span>Section 4.1.3</span></a>), the variance of <span class="math inline">\(\widehat\beta\)</span> under heteroskedasticity has the <strong>sandwich</strong> form</p>
<p><span id="eq-sandwich"><span class="math display">\[
\operatorname{Var}(\widehat\beta \mid X)
= (X^\top X)^{-1}
  \Bigl(\sum_{i=1}^n \sigma_i^2\, X_i X_i^\top\Bigr)
  (X^\top X)^{-1},
\qquad(4.8)\]</span></span></p>
<p>where <span class="math inline">\(X_i = (1, X_{i2}, \dots, X_{iK})^\top\)</span>.</p>
<ul>
<li>Under homoskedasticity it simplifies to <span class="math inline">\(\sigma^2 (X^\top X)^{-1}\)</span>.</li>
<li>The <strong>HC0</strong> estimator replaces each unknown <span class="math inline">\(\sigma_i^2\)</span> by the squared residual <span class="math inline">\(\widehat\varepsilon_i^2\)</span>.</li>
<li>The <strong>HC3</strong> estimator instead replaces <span class="math inline">\(\sigma_i^2\)</span> by <span class="math inline">\(\widehat{\varepsilon}_i^2/(1-h_{ii})^2\)</span>, where <span class="math inline">\(h_{ii}\)</span> is the leverage of observation <span class="math inline">\(i\)</span> — a small-sample correction that inflates the residuals of high-leverage observations.</li>
</ul>
<!-- 
High-leverage observations tend to have
small residuals because they pull the fitted line toward themselves; the
factor $1/(1-h_{ii})^2$ corrects for this. 
-->
</div>
</div>
</div>
</section></section><section id="sec-multipleLR-inference" class="level3" data-number="4.1.5"><h3 data-number="4.1.5" class="anchored" data-anchor-id="sec-multipleLR-inference">
<span class="header-section-number">4.1.5</span> Statistical Inference</h3>
<section id="t-tests-for-individual-coefficients" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="t-tests-for-individual-coefficients"><strong><span class="math inline">\(t\)</span>-Tests for Individual Coefficients</strong></h4>
<p>Each coefficient <span class="math inline">\(\beta_k\)</span>, <span class="math inline">\(k = 1, \dots, K\)</span>, can be tested individually. To test <span class="math display">\[\begin{align*}
&amp;H_0\colon \beta_k = 0\\[2ex]
\text{vs.}\quad &amp;H_1\colon \beta_k \neq 0,
\end{align*}\]</span> we use the <span class="math inline">\(t\)</span>-statistic <span id="eq-t-multiple"><span class="math display">\[
T_k = \frac{\widehat\beta_k - 0}{\widehat{\operatorname{SE}}(\widehat\beta_k \mid X)}
    \overset{H_0}{\sim} t_{n-K}
\qquad(4.9)\]</span></span> under <span class="math inline">\(H_0\)</span>, Assumptions 1–4, and normally distributed errors. The <span class="math inline">\(t\)</span>-distribution has <span class="math inline">\(n - K\)</span> degrees of freedom: we lose one for each of the <span class="math inline">\(K\)</span> estimated parameters, including the intercept. Without normality, this distribution holds only approximately, for large <span class="math inline">\(n\)</span> (<strong>Central Limit Theorem</strong>).</p>
<p>We reject <span class="math inline">\(H_0\)</span> at level <span class="math inline">\(\alpha\)</span> when <span class="math inline">\(T_k\)</span> is incompatible with the null hypothetical <span class="math inline">\(t_{n-K}\)</span>-distribution, i.e., when <span class="math inline">\(T_k\)</span> falls outside the <strong>critical values</strong> <span class="math inline">\(\pm t_{n-K,\,1-\alpha/2}\)</span>: <span class="math display">\[
|T_k| &gt; t_{n-K,\,1-\alpha/2}.
\]</span></p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="math inline">\(t\)</span>-Tests with Robust Standard Errors
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we use the recommended heteroskedasticity-robust HC3 standard errors <span class="math display">\[
T_k = \frac{\widehat\beta_k - 0}{\widehat{\operatorname{SE}}_{\operatorname{HC3}}(\widehat\beta_k \mid X)}
\]</span> the <span class="math inline">\(t_{n-K}\)</span>-distribution is no longer exact, even under normal errors. It remains, however, a valid distributional approximation for large <span class="math inline">\(n\)</span>, due to the Central Limit Theorem.</p>
</div>
</div>
<p><strong>Example:</strong> In the model with education, experience, and tenure <span class="math inline">\((K = 4)\)</span>, we test <span class="math display">\[\begin{align*}
&amp;H_0\colon \beta_3 = 0\quad \text{(no partial effect of experience)}\\[2ex]
\text{vs.}\quad &amp;H_1\colon \beta_3 \neq 0
\end{align*}\]</span> using HC3 standard errors. We construct the observed value of the <span class="math inline">\(t\)</span>-statistic step by step:</p>
<ol type="1">
<li><p><strong>Estimate the coefficient.</strong> The OLS estimate of <span class="math inline">\(\beta_3\)</span> is <span class="math display">\[
\widehat\beta_{3,\operatorname{obs}} = 0.0223.
\]</span></p></li>
<li><p><strong>Estimate its standard error.</strong> The HC3 standard error is the square root of the corresponding diagonal element of the HC3 variance matrix (see <a href="#sec-robustSE" class="quarto-xref"><span>Section 4.1.4</span></a>): <span class="math display">\[
\widehat{\operatorname{SE}}_{\operatorname{HC3}}(\widehat\beta_3 \mid X)_{\operatorname{obs}} = 0.0107.
\]</span></p></li>
<li><p><strong>Compute the observed <span class="math inline">\(t\)</span>-statistic.</strong> <span class="math display">\[\begin{align*}
T_{3,\operatorname{obs}}
&amp;= \frac{\widehat\beta_{3,\operatorname{obs}} - 0}{\widehat{\operatorname{SE}}_{\operatorname{HC3}}(\widehat\beta_3 \mid X)_{\operatorname{obs}}} \\[2ex]
&amp;= \frac{0.0223 - 0}{0.0107} \\[2ex]
&amp;= 2.10.
\end{align*}\]</span></p></li>
<li><p><strong>Compare with the critical value.</strong> Since <span class="math display">\[\begin{align*}
|T_{3,\operatorname{obs}}|
= 2.10
&gt; t_{n-K,\,0.975}
&amp;= t_{522,\,0.975}\\[2ex]
&amp;= 1.965,
\end{align*}\]</span> <span class="math inline">\(T_{3,\operatorname{obs}}\)</span> is incompatible with <span class="math inline">\(H_0\)</span>, and we reject <span class="math inline">\(H_0\colon \beta_3 = 0\)</span> at the <span class="math inline">\(5\%\)</span> level. The same conclusion follows from the <span class="math inline">\(p\)</span>-value, <span class="math display">\[
p_{\operatorname{obs}} = 0.037 &lt; 0.05.
\]</span></p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## HC3 variance matrix</span></span>
<span><span class="va">V_HC3</span>            <span class="op">&lt;-</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_multiple</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span>   </span>
<span><span class="co">## Step 1</span></span>
<span><span class="va">beta3_hat_obs</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_multiple</span><span class="op">)</span><span class="op">[</span><span class="st">"exper"</span><span class="op">]</span>           </span>
<span><span class="co">## Step 2</span></span>
<span><span class="va">SE_beta3_HC3_obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">V_HC3</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="st">"exper"</span><span class="op">]</span>      </span>
<span><span class="co">## Step 3</span></span>
<span><span class="va">T3_obs</span>           <span class="op">&lt;-</span> <span class="op">(</span><span class="va">beta3_hat_obs</span> <span class="op">-</span> <span class="fl">0</span><span class="op">)</span> <span class="op">/</span> <span class="va">SE_beta3_HC3_obs</span>        </span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>beta3_hat_obs    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">beta3_hat_obs</span><span class="op">)</span>,</span>
<span>  SE_beta3_HC3_obs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">SE_beta3_HC3_obs</span><span class="op">)</span>,</span>
<span>  T3_obs           <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unname.html">unname</a></span><span class="op">(</span><span class="va">T3_obs</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   beta3_hat_obs SE_beta3_HC3_obs           T3_obs 
      0.02233952       0.01066316       2.09501806 </code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## All in one step (incl. p-value):</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">lm_multiple</span>, vcov <span class="op">=</span> <span class="va">V_HC3</span><span class="op">)</span><span class="op">[</span><span class="st">"exper"</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Estimate Std. Error    t value   Pr(&gt;|t|) 
0.02233952 0.01066316 2.09501806 0.03665071 </code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Choice of Standard Errors Can Change the Conclusion
</div>
</div>
<div class="callout-body-container callout-body">
<p>With the usual non-robust standard error from <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, <span class="math display">\[
\widehat{\operatorname{SE}}(\widehat\beta_3 \mid X)_{\operatorname{obs}} = 0.0121,
\]</span> we would get <span class="math inline">\(T_{3,\operatorname{obs}} = 1.85\)</span> (<span class="math inline">\(p_{\operatorname{obs}} = 0.064\)</span>) and would fail to reject <span class="math inline">\(H_0.\)</span></p>
<p>Here, the HC3 standard error is <em>smaller</em> than the usual one: robust standard errors are not always larger.</p>
<p>Since the scatter plot in <a href="Ch_SimpleLinearRegression.html#fig-wage-educ" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> points to heteroskedasticity, the HC3-based test is the one to report.</p>
</div>
</div>
</section><section id="f-test-for-joint-significance" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="f-test-for-joint-significance"><strong><span class="math inline">\(F\)</span>-Test for Joint Significance</strong></h4>
<p>To test whether a <em>group</em> of <span class="math inline">\(q\)</span> predictors jointly matters, we use the <strong><span class="math inline">\(F\)</span>-test</strong>.</p>
<p><strong>Example: Does the region matter?</strong> The <code>wage1</code> data contain three binary (dummy) variables for the region a worker lives in:</p>
<ul>
<li>
<code>northcen</code> <span class="math inline">\(= 1\)</span> if the worker lives in the north-central U.S., and <span class="math inline">\(= 0\)</span> otherwise,</li>
<li>
<code>south</code> <span class="math inline">\(= 1\)</span> if the worker lives in the South, and <span class="math inline">\(= 0\)</span> otherwise, and</li>
<li>
<code>west</code> <span class="math inline">\(= 1\)</span> if the worker lives in the West, and <span class="math inline">\(= 0\)</span> otherwise.</li>
</ul>
<p>For instance, <span class="math inline">\(\text{northcen}_i = 1\)</span> means that worker <span class="math inline">\(i\)</span> lives in the north-central region, and <span class="math inline">\(\text{northcen}_i = 0\)</span> means that worker <span class="math inline">\(i\)</span> does <em>not</em> live there. Workers in the fourth region, the Northeast, have all three dummies equal to zero. They serve as the <strong>reference group</strong>: a separate dummy for the Northeast is left out of the model to avoid perfect multicollinearity (see <a href="#sec-genderGap" class="quarto-xref"><span>Section 4.1.6</span></a> for more on binary predictors).</p>
<p>We add the three region dummies to the model with education, experience, and tenure: <span class="math display">\[
\begin{aligned}
Y_i = \beta_1 &amp;+ \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i + \beta_4\,\text{tenure}_i \\
              &amp;+ \beta_5\,\text{northcen}_i + \beta_6\,\text{south}_i + \beta_7\,\text{west}_i + \varepsilon_i.
\end{aligned}
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_region</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span> <span class="op">+</span> <span class="va">tenure</span> <span class="op">+</span> <span class="va">northcen</span> <span class="op">+</span> <span class="va">south</span> <span class="op">+</span> <span class="va">west</span>,</span>
<span>                data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="co">## t-tests with HC3 standard errors</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">lm_region</span>,</span>
<span>         vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_region</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"northcen"</span>, <span class="st">"south"</span>, <span class="st">"west"</span><span class="op">)</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Estimate Std. Error    t value  Pr(&gt;|t|)
northcen -0.6567425  0.4103033 -1.6006268 0.1100681
south    -0.4918371  0.3722884 -1.3211184 0.1870440
west      0.4664741  0.4895435  0.9528756 0.3410967</code></pre>
</div>
</div>
<p>None of the three region coefficients is individually significant at the <span class="math inline">\(5\%\)</span> level: all <span class="math inline">\(p\)</span>-values of the individual <span class="math inline">\(t\)</span>-tests (with HC3 standard errors) exceed <span class="math inline">\(0.05\)</span>.</p>
<p>Does this mean that the region does not matter? Not necessarily! The question</p>
<div style="text-align: center;">
<p>“Does the region matter at all?”</p>
</div>
<p>is a <strong><em>joint</em> hypothesis</strong> about all three coefficients: <span class="math display">\[\begin{align*}
&amp;H_0\colon \beta_5 = \beta_6 = \beta_7 = 0\quad\text{(the region does not matter)}\\[2ex]
\text{vs.}\quad &amp;H_1\colon \text{at least one of } \beta_5, \beta_6, \beta_7 \text{ is } \neq 0,
\end{align*}\]</span> with <span class="math inline">\(q = 3\)</span> restrictions (three coefficients set to zero).</p>
<p>The idea of the <span class="math inline">\(F\)</span>-test is to compare two models:</p>
<ul>
<li>the <strong>unrestricted model</strong> with all <span class="math inline">\(K\)</span> parameters (here: <span class="math inline">\(K = 7\)</span>), against</li>
<li>the <strong>restricted model</strong>, in which the <span class="math inline">\(q\)</span> coefficients under <span class="math inline">\(H_0\)</span> are set to zero (here: the model without the region dummies).</li>
</ul>
<p>If <span class="math inline">\(H_0\)</span> is true, dropping the <span class="math inline">\(q\)</span> predictors should increase the sum of squared residuals only a little. The <span class="math inline">\(F\)</span>-statistic measures this increase, relative to the unexplained variation of the unrestricted model: <span id="eq-F-stat"><span class="math display">\[
F = \frac{\frac{1}{q}\Bigl(\sum_{i=1}^{n}\widehat\varepsilon_{i,\text{restr}}^2 - \sum_{i=1}^{n}\widehat\varepsilon_{i}^2\Bigr)}
         {\frac{1}{n-K}\sum_{i=1}^{n}\widehat\varepsilon_i^2}
  \overset{H_0}{\sim} F_{q,\;n-K}
\qquad(4.10)\]</span></span> under <span class="math inline">\(H_0\)</span>, Assumptions 1–4, and normally distributed errors, where</p>
<ul>
<li>
<span class="math inline">\(F_{q,\;n-K}\)</span> denotes the <span class="math inline">\(F\)</span>-distribution with <span class="math inline">\(q\)</span> numerator and <span class="math inline">\(n-K\)</span> denominator degrees of freedom (<a href="Ch_ReviewProbStats.html#sec-fdistrib" class="quarto-xref"><span>Section 2.6.3</span></a>),</li>
<li>
<span class="math inline">\(\widehat\varepsilon_{i,\text{restr}}\)</span> are the residuals of the restricted model, and</li>
<li>
<span class="math inline">\(\widehat\varepsilon_i\)</span> are the residuals of the unrestricted model.</li>
</ul>
<p>Large values of <span class="math inline">\(F\)</span> are incompatible with <span class="math inline">\(H_0\)</span>: we reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[
F_{\operatorname{obs}} &gt; F_{q,\,n-K,\,1-\alpha},
\]</span> where <span class="math inline">\(F_{q,\,n-K,\,1-\alpha}\)</span> denotes the <span class="math inline">\((1-\alpha)\)</span>-quantile of the <span class="math inline">\(F_{q,\,n-K}\)</span>-distribution.</p>
<p>Unlike the <span class="math inline">\(t\)</span>-statistic <span class="math inline">\(T\)</span>, the <span class="math inline">\(F\)</span>-statistic cannot be negative, so only large values count against <span class="math inline">\(H_0.\)</span></p>
<p><strong>Robust <span class="math inline">\(F\)</span>-test.</strong> Like the usual standard errors, the <span class="math inline">\(F\)</span>-statistic in <a href="#eq-F-stat" class="quarto-xref">Equation&nbsp;<span>4.10</span></a> assumes homoskedastic errors. Since the wage data are heteroskedastic, we use its heteroskedasticity-robust (HC3) version instead — consistent with the HC3-based <span class="math inline">\(t\)</span>-tests above. The robust <span class="math inline">\(F\)</span>-statistic measures the same thing (how strongly the data contradict the <span class="math inline">\(q\)</span> restrictions under <span class="math inline">\(H_0\)</span>), but it is computed from the HC3 variance matrix of the estimated coefficients; see the “Going Deeper” box below.</p>
<p>Under <span class="math inline">\(H_0\)</span>, the robust version of the <span class="math inline">\(F\)</span>-statistic is approximately <span class="math inline">\(F_{q,\,n-K}\)</span>-distributed for large <span class="math inline">\(n\)</span>, and the decision rule stays the same.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: The Robust <span class="math inline">\(F\)</span>-Statistic
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This box requires matrix algebra; see <a href="Ch_MatrixAlgebra.html" class="quarto-xref"><span>Appendix A</span></a>.</p>
<p>Collect the <span class="math inline">\(q\)</span> coefficients under test in the vector <span class="math inline">\(\theta\)</span> (here: <span class="math inline">\(\theta = (\beta_5, \beta_6, \beta_7)^\top\)</span>), so that <span class="math inline">\(H_0\colon \theta = 0\)</span>. Let <span class="math inline">\(\widehat\theta\)</span> be their OLS estimates and <span class="math inline">\(\widehat V_{\operatorname{HC3}}\)</span> the corresponding <span class="math inline">\((q \times q)\)</span> block of the HC3 variance matrix of <span class="math inline">\(\widehat\beta\)</span>. The robust <span class="math inline">\(F\)</span>-statistic is <span class="math display">\[
F_{\operatorname{HC3}} = \frac{1}{q}\, \widehat\theta^\top \, \widehat V_{\operatorname{HC3}}^{-1} \, \widehat\theta.
\]</span> For <span class="math inline">\(q = 1\)</span>, it reduces to the square of the robust <span class="math inline">\(t\)</span>-statistic, <span class="math inline">\(F_{\operatorname{HC3}} = T_{\operatorname{HC3}}^2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">theta_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_region</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"northcen"</span>, <span class="st">"south"</span>, <span class="st">"west"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">V_theta</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_region</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">theta_hat</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">theta_hat</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">F_by_hand</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/drop.html">drop</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">theta_hat</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="va">V_theta</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">theta_hat</span><span class="op">)</span> <span class="op">/</span> <span class="fl">3</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>F_by_hand <span class="op">=</span> <span class="va">F_by_hand</span>,</span>
<span>  F_by_R    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/waldtest.html">waldtest</a></span><span class="op">(</span><span class="va">lm_multiple</span>, <span class="va">lm_region</span>,</span>
<span>                       vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_region</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="cn">F</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F_by_hand    F_by_R 
 2.683162  2.683162 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>In R, <code><a href="https://rdrr.io/pkg/lmtest/man/waldtest.html">waldtest()</a></code> from the <code>lmtest</code> package compares the restricted and the unrestricted model using HC3 standard errors:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/waldtest.html">waldtest</a></span><span class="op">(</span><span class="va">lm_multiple</span>, <span class="va">lm_region</span>, </span>
<span>         vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_region</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: wage ~ educ + exper + tenure
Model 2: wage ~ educ + exper + tenure + northcen + south + west
  Res.Df Df      F  Pr(&gt;F)  
1    522                    
2    519  3 2.6832 0.04611 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><span class="math inline">\(F_{\operatorname{obs}} = 2.68 &gt; F_{3,\,519,\,0.95} = 2.62\)</span></li>
<li>
<span class="math inline">\(p\)</span>-value: <span class="math inline">\(p_{\operatorname{obs}} = 0.046\)</span>)</li>
</ul>
<p>Thus, we reject <span class="math inline">\(H_0\)</span> at the <span class="math inline">\(5\%\)</span> level: the region matters for wages, even though none of the three region dummies is significant on its own.</p>
<p>Each individual <span class="math inline">\(t\)</span>-test only asks whether <em>one</em> region differs from the reference region <code>northeast</code>; the <span class="math inline">\(F\)</span>-test combines the evidence from all three. Testing predictors one by one can therefore miss what they explain together.</p>
</section><section id="the-default-overall-f-test" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="the-default-overall-f-test"><strong>The Default Overall <span class="math inline">\(F\)</span>-test</strong></h4>
<p>The standard <span class="math inline">\(F\)</span>-test reported by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> is the special case that tests <strong><em>all</em> slopes</strong> at once: <span class="math display">\[\begin{align*}
&amp;H_0\colon \beta_2 = \dots = \beta_K = 0\quad\text{(none of the predictors matters)}\\[2ex]
\text{vs.}\quad &amp;H_1\colon \text{at least one of } \beta_2,\dots,\beta_K \text{ is } \neq 0,
\end{align*}\]</span> with <span class="math inline">\(q = K - 1\)</span> restrictions. In this case, the <span class="math inline">\(F\)</span>-statistic from <a href="#eq-F-stat" class="quarto-xref">Equation&nbsp;<span>4.10</span></a> simplifies to <span class="math display">\[
F = \frac{\displaystyle\frac{1}{K-1}\sum_{i=1}^{n}(\widehat Y_i - \bar Y)^2}
         {\displaystyle\frac{1}{n-K}\sum_{i=1}^{n}\widehat\varepsilon_i^2}
  \overset{H_0}{\sim} F_{K-1,\;n-K}.
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Going Deeper: Derivation of the Overall <span class="math inline">\(F\)</span>-Statistic
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>
<strong>The restricted model.</strong> Under <span class="math inline">\(H_0\)</span>, all slopes are zero, so the restricted model contains only the intercept: <span class="math display">\[
Y_i = \beta_1 + \varepsilon_i.
\]</span>
</li>
<li>
<strong>Its OLS estimate and residuals.</strong> The OLS estimate of <span class="math inline">\(\beta_1\)</span> in this model is the sample mean, <span class="math inline">\(\widehat\beta_1 = \bar Y\)</span>, since <span class="math inline">\(\bar Y\)</span> minimizes <span class="math inline">\(\sum_{i=1}^n (Y_i - b_1)^2\)</span>. The residuals of the restricted model are therefore <span class="math display">\[
\widehat\varepsilon_{i,\text{restr}} = Y_i - \bar Y,
\qquad\text{so}\qquad
\sum_{i=1}^{n}\widehat\varepsilon_{i,\text{restr}}^2 = \sum_{i=1}^{n}(Y_i - \bar Y)^2,
\]</span> which is the total variation of the outcome.</li>
<li>
<strong>The numerator.</strong> By the decomposition of the total variation into an explained and an unexplained part (see <a href="Ch_ExtendingLinearRegression.html#eq-SS-decomp" class="quarto-xref">Equation&nbsp;<span>5.3</span></a>), <span class="math display">\[
\sum_{i=1}^{n}(Y_i - \bar Y)^2 = \sum_{i=1}^{n}(\widehat Y_i - \bar Y)^2 + \sum_{i=1}^{n}\widehat\varepsilon_i^2,
\]</span> the difference of the residual sums of squares in the numerator of <a href="#eq-F-stat" class="quarto-xref">Equation&nbsp;<span>4.10</span></a> is exactly the variation explained by the unrestricted model: <span class="math display">\[
\sum_{i=1}^{n}\widehat\varepsilon_{i,\text{restr}}^2 - \sum_{i=1}^{n}\widehat\varepsilon_i^2
= \sum_{i=1}^{n}(\widehat Y_i - \bar Y)^2.
\]</span>
</li>
<li>
<strong>The <span class="math inline">\(F\)</span>-statistic.</strong> Plugging this into <a href="#eq-F-stat" class="quarto-xref">Equation&nbsp;<span>4.10</span></a> with <span class="math inline">\(q = K - 1\)</span> gives the simplified <span class="math inline">\(F\)</span>-statistic above.</li>
</ol>
</div>
</div>
</div>
<p>In words: the overall <span class="math inline">\(F\)</span>-statistic compares the variation <strong>explained</strong> by the predictors (per restriction) with the variation that remains <strong>unexplained</strong> (per degree of freedom). If none of the predictors matters, both parts are of similar size and <span class="math inline">\(F\)</span> is close to <span class="math inline">\(1\)</span>; large values of <span class="math inline">\(F\)</span> indicate that the model explains much more than the intercept alone.</p>
<p><code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> reports this homoskedasticity-based version. Consistent with the tests above, we use its robust (HC3) version, which is obtained by calling <code><a href="https://rdrr.io/pkg/lmtest/man/waldtest.html">waldtest()</a></code> with only one model; the restricted model is then the intercept-only model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/waldtest.html">waldtest</a></span><span class="op">(</span><span class="va">lm_region</span>, vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_region</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test

Model 1: wage ~ educ + exper + tenure + northcen + south + west
Model 2: wage ~ 1
  Res.Df Df    F    Pr(&gt;F)    
1    519                      
2    525 -6 21.1 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>For the region model, <span class="math inline">\(F_{\operatorname{obs}} = 21.1\)</span> with a <span class="math inline">\(p\)</span>-value that is essentially zero: the predictors jointly matter — no surprise, given the strong effects of education and tenure.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
For Comparison: The Classic <span class="math inline">\(F\)</span>-Test
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under homoskedasticity, the classic <span class="math inline">\(F\)</span>-test from <a href="#eq-F-stat" class="quarto-xref">Equation&nbsp;<span>4.10</span></a> can be computed with <code>anova(lm_multiple, lm_region)</code>. For the region example, it gives <span class="math inline">\(F_{\operatorname{obs}} = 3.03\)</span> (<span class="math inline">\(p_{\operatorname{obs}} = 0.029\)</span>) — here, the conclusion is the same as with the robust test.</p>
</div>
</div>
<!-- 
#### **Size, Power, and Consistency** {-}

Recall the two possible errors of a test from @tbl-test-decisions. The
probability of a Type I error is called the **size** of the test; our
decision rules are designed such that the size equals the significance
level $\alpha$. The probability of correctly rejecting a false $H_0$ is
called the **power** of the test:
$$
\text{power} = P(\text{reject $H_0$} \mid \text{$H_1$ is true}) = 1 - P(\text{Type II error}).
$$
Unlike the size, the power is not fixed by us: it depends on the unknown
true value of $\beta_k$.

For the $t$-test of $H_0\colon \beta_k = 0$, the power increases

* with the distance $|\beta_k|$ of the true value from zero,
* with the sample size $n$, and
* with the variation in the predictor $X_{ik}$,

because each of these makes $\widehat\beta_k$ more precise relative to the
distance to be detected (compare @eq-var-beta2).

The reason why larger samples help is **consistency**. Under Assumptions
1–3, the OLS estimators are **consistent**: as $n \to \infty$, the
standard deviation of $\widehat\beta_k$ shrinks to zero, and
$\widehat\beta_k$ converges in probability to the true value,
$\widehat\beta_k \xrightarrow{p} \beta_k$, i.e.,
$P(|\widehat\beta_k - \beta_k| > c) \to 0$ for every $c > 0$. As a
consequence, for any fixed $\beta_k \neq 0$, the power of the $t$-test
tends to $1$ as $n \to \infty$. With small samples, by contrast, even
economically important effects may not be statistically significant. 

-->
</section></section><section id="sec-genderGap" class="level3" data-number="4.1.6"><h3 data-number="4.1.6" class="anchored" data-anchor-id="sec-genderGap">
<span class="header-section-number">4.1.6</span> A Binary Predictor: The Gender Wage Gap</h3>
<p>The variable <code>female</code> is a <strong>binary (dummy) variable</strong>: <span class="math display">\[
\text{female}_i =
\begin{cases}
1 &amp; \text{if worker $i$ is female},\\
0 &amp; \text{if worker $i$ is male}.
\end{cases}
\]</span> Adding it to the model with education, experience, and tenure gives</p>
<p><span id="eq-gender-model"><span class="math display">\[
\begin{aligned}
Y_i = \beta_1 &amp;+ \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i \\
              &amp;+ \beta_4\,\text{tenure}_i + \beta_5\,\text{female}_i + \varepsilon_i.
\end{aligned}
\qquad(4.11)\]</span></span></p>
<p>Since <span class="math inline">\(\text{female}_i\)</span> takes only the values <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>, the conditional mean of wages splits into two cases:</p>
<ul>
<li>
<strong>Men</strong> (<span class="math inline">\(\text{female}_i = 0\)</span>): <span class="math display">\[\begin{align*}
&amp;E(Y_i \mid \text{educ}_i, \text{exper}_i, \text{tenure}_i, \text{female}_i = 0) \\
&amp;\quad= \beta_1 + \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i + \beta_4\,\text{tenure}_i
\end{align*}\]</span>
</li>
<li>
<strong>Women</strong> (<span class="math inline">\(\text{female}_i = 1\)</span>): <span class="math display">\[\begin{align*}
&amp;E(Y_i \mid \text{educ}_i, \text{exper}_i, \text{tenure}_i, \text{female}_i = 1) \\
&amp;\quad= (\beta_1 + \beta_5) + \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i + \beta_4\,\text{tenure}_i
\end{align*}\]</span>
</li>
</ul>
<p>The two conditional means differ only in their intercepts: for fixed experience and tenure, they are two <strong>parallel lines</strong> in education. Men are the <strong>reference group</strong> (all-zero dummy), and</p>
<p><span class="math display">\[
\beta_5 = E(Y_i \mid \ldots, \text{female}_i = 1) - E(Y_i \mid \ldots, \text{female}_i = 0)
\]</span></p>
<p>is the <strong>adjusted wage gap</strong>: the expected wage difference between women and men with identical education, experience, and tenure.</p>
<p>As in the region example, we must not add a second dummy <code>male</code> <span class="math inline">\(= 1 - \text{female}\)</span>: together with the intercept, this would cause perfect multicollinearity.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_gender</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span> <span class="op">+</span> <span class="va">tenure</span> <span class="op">+</span> <span class="va">female</span>,</span>
<span>                data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">lm_gender</span>, vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_gender</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) -1.567939   0.838449 -1.8700   0.06204 .  
educ         0.571505   0.062161  9.1939 &lt; 2.2e-16 ***
exper        0.025396   0.009919  2.5603   0.01074 *  
tenure       0.141005   0.028516  4.9447 1.030e-06 ***
female      -1.810852   0.255858 -7.0776 4.762e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> <span class="math inline">\(\widehat\beta_5 = -1.81\)</span>: women earn on average $1.81 per hour less than men with the same education, experience, and tenure. With HC3 standard errors, <span class="math inline">\(T_{5,\operatorname{obs}} = -7.08\)</span> and the <span class="math inline">\(p\)</span>-value is essentially zero, so we can reject the null hypothesis <span class="math display">\[
H_0\colon \beta_5 = 0\quad\text{(no adjusted wage gap)}.
\]</span></p>
<p><a href="#fig-gender-lines" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> shows the two fitted lines, evaluated at the sample means of experience and tenure:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-gender-lines" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-gender-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Ch_MultipleLinearRegression_files/figure-html/fig-gender-lines-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gender-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Fitted wage-education lines for men (blue) and women (red) from the model in <a href="#eq-gender-model" class="quarto-xref">Equation&nbsp;<span>4.11</span></a>, evaluated at mean experience and tenure. Parallel lines impose identical returns to education for both groups.
</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code: Plotting the Fitted Wage Lines for Men and Women
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">beta</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_gender</span><span class="op">)</span></span>
<span><span class="va">exper_bar</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">exper</span><span class="op">)</span></span>
<span><span class="va">tenure_bar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">tenure</span><span class="op">)</span></span>
<span><span class="va">educ_seq</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">18</span>, length.out <span class="op">=</span> <span class="fl">200</span><span class="op">)</span></span>
<span></span>
<span><span class="va">wage_men</span>   <span class="op">&lt;-</span> <span class="va">beta</span><span class="op">[</span><span class="st">"(Intercept)"</span><span class="op">]</span> <span class="op">+</span></span>
<span>              <span class="va">beta</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span>   <span class="op">*</span> <span class="va">educ_seq</span>   <span class="op">+</span></span>
<span>              <span class="va">beta</span><span class="op">[</span><span class="st">"exper"</span><span class="op">]</span>  <span class="op">*</span> <span class="va">exper_bar</span>  <span class="op">+</span></span>
<span>              <span class="va">beta</span><span class="op">[</span><span class="st">"tenure"</span><span class="op">]</span> <span class="op">*</span> <span class="va">tenure_bar</span></span>
<span><span class="va">wage_women</span> <span class="op">&lt;-</span> <span class="va">wage_men</span> <span class="op">+</span> <span class="va">beta</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span></span>
<span></span>
<span><span class="va">pt_col</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">female</span> <span class="op">==</span> <span class="fl">1</span>,</span>
<span>                 <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="st">"tomato"</span>,    alpha.f <span class="op">=</span> <span class="fl">0.35</span><span class="op">)</span>,</span>
<span>                 <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="st">"steelblue"</span>, alpha.f <span class="op">=</span> <span class="fl">0.35</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/jitter.html">jitter</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">educ</span>, factor <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span>, <span class="va">wage1</span><span class="op">$</span><span class="va">wage</span>,</span>
<span>     col <span class="op">=</span> <span class="va">pt_col</span>, pch <span class="op">=</span> <span class="fl">16</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Education (years)"</span>, ylab <span class="op">=</span> <span class="st">"Hourly Wage (USD)"</span>,</span>
<span>     las  <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">educ_seq</span>, <span class="va">wage_men</span>,   col <span class="op">=</span> <span class="st">"steelblue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">educ_seq</span>, <span class="va">wage_women</span>, col <span class="op">=</span> <span class="st">"tomato"</span>,    lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topleft"</span>,</span>
<span>       legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Men"</span>, <span class="st">"Women"</span><span class="op">)</span>,</span>
<span>       col    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"steelblue"</span>, <span class="st">"tomato"</span><span class="op">)</span>,</span>
<span>       lwd    <span class="op">=</span> <span class="fl">2</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>The model in <a href="#eq-gender-model" class="quarto-xref">Equation&nbsp;<span>4.11</span></a> <em>assumes</em> equal returns to education for men and women — the lines are parallel by construction. We relax this restriction in the next subsection.</p>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Business Takeaway: Raw vs.&nbsp;Adjusted Pay Gap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pay-equity analyses distinguish two numbers:</p>
<ul>
<li>The <strong>raw gap</strong> is the difference in average wages: women in the sample earn $2.51 per hour less than men.</li>
<li>The <strong>adjusted gap</strong> <span class="math inline">\(\widehat\beta_5\)</span> compares women and men with the same education, experience, and tenure: $1.81 per hour.</li>
</ul>
<p>About 72% of the raw gap remains after accounting for these characteristics. Neither number settles the question of discrimination on its own: the adjusted gap may reflect omitted characteristics, and the “explained” part may itself reflect unequal opportunities — for example, if women were given fewer chances to build up tenure. Controlling for such variables is the “bad control” problem from <a href="#sec-OVB" class="quarto-xref"><span>Section 4.1.1</span></a>.</p>
</div>
</div>
</section><section id="sec-interactions" class="level3" data-number="4.1.7"><h3 data-number="4.1.7" class="anchored" data-anchor-id="sec-interactions">
<span class="header-section-number">4.1.7</span> Interaction Effects: Do Returns to Education Differ by Gender?</h3>
<p>To allow different returns to education for men and women, we add the <strong>interaction term</strong> <span class="math inline">\(\text{educ}_i \times \text{female}_i\)</span> — the product of the two predictors — to the model in <a href="#eq-gender-model" class="quarto-xref">Equation&nbsp;<span>4.11</span></a>:</p>
<p><span id="eq-interact-model"><span class="math display">\[
\begin{aligned}
Y_i = \beta_1 &amp;+ \beta_2\,\text{educ}_i + \beta_3\,\text{exper}_i
               + \beta_4\,\text{tenure}_i \\
              &amp;+ \beta_5\,\text{female}_i
               + \beta_6\,(\text{educ}_i \times \text{female}_i) + \varepsilon_i.
\end{aligned}
\qquad(4.12)\]</span></span></p>
<p>The slope on education now differs by gender:</p>
<ul>
<li>
<strong>Men</strong> (<span class="math inline">\(\text{female}_i = 0\)</span>): slope <span class="math inline">\(\beta_2\)</span>
</li>
<li>
<strong>Women</strong> (<span class="math inline">\(\text{female}_i = 1\)</span>): slope <span class="math inline">\(\beta_2 + \beta_6\)</span>
</li>
</ul>
<p>So <span class="math inline">\(\beta_6\)</span> is the <strong>difference in the return to education</strong> between women and men.</p>
<p>Note that <span class="math inline">\(\beta_5\)</span> alone now measures the gender gap at <span class="math inline">\(\text{educ}_i = 0\)</span>, which is not a meaningful comparison.</p>
<p>The gap at education level <span class="math inline">\(\text{educ}_i = x\)</span> is given by <span class="math display">\[
\beta_5 + \beta_6\, x.
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_interact</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span> <span class="op">+</span> <span class="va">tenure</span> <span class="op">+</span> <span class="va">female</span> <span class="op">+</span> <span class="va">educ</span><span class="op">:</span><span class="va">female</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lmtest/man/coeftest.html">coeftest</a></span><span class="op">(</span><span class="va">lm_interact</span>, vcov <span class="op">=</span> <span class="fu"><a href="https://sandwich.R-Forge.R-project.org/reference/vcovHC.html">vcovHC</a></span><span class="op">(</span><span class="va">lm_interact</span>, type <span class="op">=</span> <span class="st">"HC3"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

              Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) -2.2746052  0.9506849 -2.3926  0.017084 *  
educ         0.6257699  0.0720213  8.6887 &lt; 2.2e-16 ***
exper        0.0256299  0.0098929  2.5907  0.009846 ** 
tenure       0.1423329  0.0285324  4.9885 8.311e-07 ***
female      -0.0600146  1.4888493 -0.0403  0.967862    
educ:female -0.1397386  0.1241764 -1.1253  0.260971    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-interact-lines" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interact-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Ch_MultipleLinearRegression_files/figure-html/fig-interact-lines-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interact-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Fitted wage-education lines for men (blue) and women (red) from the interaction model, evaluated at mean experience and tenure. The lines are no longer forced to be parallel.
</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code: Plotting the Fitted Lines of the Interaction Model
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">b</span>        <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm_interact</span><span class="op">)</span></span>
<span><span class="va">wage_men</span> <span class="op">&lt;-</span> <span class="va">b</span><span class="op">[</span><span class="st">"(Intercept)"</span><span class="op">]</span> <span class="op">+</span></span>
<span>            <span class="va">b</span><span class="op">[</span><span class="st">"educ"</span><span class="op">]</span>   <span class="op">*</span> <span class="va">educ_seq</span>   <span class="op">+</span></span>
<span>            <span class="va">b</span><span class="op">[</span><span class="st">"exper"</span><span class="op">]</span>  <span class="op">*</span> <span class="va">exper_bar</span>  <span class="op">+</span></span>
<span>            <span class="va">b</span><span class="op">[</span><span class="st">"tenure"</span><span class="op">]</span> <span class="op">*</span> <span class="va">tenure_bar</span></span>
<span><span class="va">wage_women</span> <span class="op">&lt;-</span> <span class="va">wage_men</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="st">"female"</span><span class="op">]</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="st">"educ:female"</span><span class="op">]</span> <span class="op">*</span> <span class="va">educ_seq</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/jitter.html">jitter</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">$</span><span class="va">educ</span>, factor <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span>, <span class="va">wage1</span><span class="op">$</span><span class="va">wage</span>,</span>
<span>     col <span class="op">=</span> <span class="va">pt_col</span>, pch <span class="op">=</span> <span class="fl">16</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Education (years)"</span>, ylab <span class="op">=</span> <span class="st">"Hourly Wage (USD)"</span>,</span>
<span>     las  <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">educ_seq</span>, <span class="va">wage_men</span>,   col <span class="op">=</span> <span class="st">"steelblue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">educ_seq</span>, <span class="va">wage_women</span>, col <span class="op">=</span> <span class="st">"tomato"</span>,    lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topleft"</span>,</span>
<span>       legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Men"</span>, <span class="st">"Women"</span><span class="op">)</span>,</span>
<span>       col    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"steelblue"</span>, <span class="st">"tomato"</span><span class="op">)</span>,</span>
<span>       lwd    <span class="op">=</span> <span class="fl">2</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The point estimate <span class="math inline">\(\widehat\beta_6 = -0.14\)</span> says that each additional year of education raises women’s hourly wages by about 14 cents less than men’s. However, the estimate is imprecise (<span class="math inline">\(p = 0.26\)</span> with HC3 standard errors): the data are also consistent with equal returns to education, i.e., with the parallel lines of <a href="#fig-gender-lines" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>.</p>
</section></section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Long_Ervin_2000" class="csl-entry" role="listitem">
Long, J Scott, and Laurie H Ervin. 2000. <span>“Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model.”</span> <em>The American Statistician</em> 54 (3): 217–24.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./Ch_SimpleLinearRegression.html" class="pagination-link" aria-label="Simple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_ExtendingLinearRegression.html" class="pagination-link" aria-label="Extending and Evaluating the Linear Model">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Extending and Evaluating the Linear Model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>